- name: add repo keys
  become: yes
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - https://packages.microsoft.com/keys/microsoft.asc
    - https://dl.yarnpkg.com/debian/pubkey.gpg
    - https://download.docker.com/linux/ubuntu/gpg

- name: add repos
  become: yes
  apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.filename}}"
    state: present
  with_items:
    - {
        filename: "vscode",
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main",
      }
    - {
        filename: "yarn",
        repo: "deb https://dl.yarnpkg.com/debian/ stable main",
      }
    - {
        filename: "docker-ce",
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable",
      }


- name: install basic
  become: yes
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common


- name: install fonts
  become: yes
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - fonts-firacode
    - fonts-powerline

- name: install commons
  become: yes
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - keepassxc  
    - terminator
    - vim
    - zsh


- name: install deveolopment tools
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - code
    - yarn
    - docker-ce
    - openjdk-8-jdk
    - openjdk-11-jdk

- name: install jenv
  git:
    repo: https://github.com/gcuisinier/jenv.git
    dest: ~/.jenv

- name: install autoenv
  git:
    repo: https://github.com/kennethreitz/autoenv.git
    dest: ~/.autoenv

 

- name: install utilities
  become: true
  apt:
    deb: "{{ item }}"
  with_items:
    - https://download.opensuse.org/repositories/home:/colomboem/xUbuntu_12.04/amd64/dukto_6.0-1_amd64.deb