---
# Main configuration
# -------------------

miniconda_url: http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh

miniconda_home: '~/miniconda'

miniconda_environments:
  - name: pytorch
    python_version: 3.6
    pkgs: 'pip ipython'

  - name: tensorflow
    python_version: 3.6
    pkgs: 'pip ipython'

miniconda_modify_path: no
miniconda_rcfile: '~/.bashrc'

miniconda_add_condarc: yes