- name: add repo keys
  become: yes
  apt_key:
    url: "{{ item }}"
    state: present
  with_items:
    - https://packages.microsoft.com/keys/microsoft.asc
    - https://dl.yarnpkg.com/debian/pubkey.gpg
    - https://download.docker.com/linux/ubuntu/gpg

- name: add repos
  become: yes
  apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.filename}}"
    state: latest
  with_items:
    - {
        filename: "vscode",
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main",
      }
    - {
        filename: "yarn",
        repo: "deb https://dl.yarnpkg.com/debian/ stable main",
      }
    - {
        filename: "docker-ce",
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable",
      }

- name: install deveolopment tools
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - code
    - yarn
    - docker-ce
    - openjdk-8-jdk
    - openjdk-11-jdk

- name: install jenv
  git:
    repo: https://github.com/gcuisinier/jenv.git
    dest: ~/.jenv

- name: install autoenv
  git:
    repo: https://github.com/kennethreitz/autoenv.git
    dest: ~/.autoenv

- name: instal virtualbox vagrant
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - virtualbox
    - vagrant

# - name: install android studio
#   become: true
#   command: snap install android-studio --classic
